### PR TITLE
Refactor project

### PR DESCRIPTION
**Pull request by e2**
- use Guard::Compat
- setup Guard::RSpec
- setup Guard::RuboCop
- fix RuboCop offenses
- break up main class into smaller (by responsibilities)
- rebase to imathis/master

### CODE REVIEW

**Comment by bvsatyaram** [comment]
+1
Start the game already!

**Comment by e2** [comment]
LiveReload doesn't work with Thin on this branch. 

It works when running in a separate Guard instance (using Guard groups), so I'm guessing LiveReload's EventMachine doesn't play well with fork().

This means it may be currently not possible to have "everything working" within a single Guard instance.

The only idea I have is to run Rack as a child process, and not through fork().

**Comment by e2** [comment]
Also, the `build` method in `action.rb` should catch `StandardError` exception, because that's what `Haml` errors are based on, and jekyll throws what it gets.

**Comment by e2** [comment]
The StandardError should also be caught in `Builder::Rebuilder#update`.

The real fix is here: https://github.com/jekyll/jekyll/issues/3289 (but it may take a long time before a change is released).

**Comment by imathis** [comment]
I'm sorry it's taking me so long to review this. I'm in the middle of working on a big release for Octopress and these are a lot of changes to digest. Do you know if these regressions due to the refactor or are they issues with being incompatible with newer versions of dependencies?

**Comment by e2** [comment]
I never got guard-jekyll-plus to work completely as intended (or as I wanted), so I'm only using this branch.

These issues are nothing new:
- using threads (and Webrick) for server interferes with Jekyll
- using fork for server interferes with LiveReload (EventMachine probably has to be forked in a special way)

I can't reasonably send more PRs (or add issues) until you merge this into master.

This PR isn't different from the current master besides the few points that I described.

Besides, LiveReload won't work if you have `ignore /^_site/` in your Guardfile template (ignore works globally).

**Comment by imathis** [comment]
Looks good. On to the future :)

**Pull request merged**
