### PR TITLE
Standardizing module name and paths. Fixes #33

### LINKED ISSUE #33: module name does not match file path by any convention
expected: `guard/jekyll_plus{.rb,/**{` and `module Guard::JekyllPlus`
actual: `guard/jekyll-plus{.rb,/**}` and `module Guard::Jekyllplus`

acceptable alternative: `guard/jekyllplus{.rb,/**}` and `module Guard::Jekyllplus`

Problem: mostly with the template (`guard init`), although both Guard and plugins should adopt a single convention (and deprecate everything else).

Reference: http://guides.rubygems.org/name-your-gem/

It's up to you to decide whether you want to change the module name or the file names - if you make the changes and commit to master, I'll make sure they work in Guard.

### PR DESCRIPTION
**Pull request by imathis**
Changed from `'jekyll-plus'` and `Jekyllplus` to `:jekyll_plus` and `JekyllPlus`
@e2 how do you feel about this?

### CODE REVIEW

**Comment by e2** [comment]
Looks fine.

The gem name doesn't match, but that shouldn't be an issue with Guard.

I'll need #32 merged into master before I test this though (mostly since I want to add tests).

No rush with this - I have stuff to do as well.

**Comment by imathis** [comment]
@e2 I've updated this PR to be a module rename on the current master. Tests are passing, do you see any issues or shall I merge it.

**Comment by e2** [comment]
Merge it to master. If if works from master, it's fine. If it doesn't or it's preventing a release - mention me in the issue and I'll check it out and create a PR as necessary.

This requires a bit of work to do properly, which means it won't happen soon - so let me know if you're blocked by this (e.g. if `guard init` doesn't work or doesn't work properly) and I'll create a quickfix.

Just to give you a sense of all the scenario I'd have to test for every plugin: 

https://github.com/guard/guard-compat/issues/1

**Comment by imathis** [comment]
Ok thanks for your help!

**Pull request merged**
